# Generated by Django 6.0.3 on 2026-03-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('revenue', 'Revenue'), ('users', 'Usuarios Activos'), ('conversion', 'Tasa de Conversión'), ('churn', 'Churn Rate'), ('mrr', 'MRR'), ('arr', 'ARR'), ('cac', 'CAC'), ('ltv', 'LTV')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('$', 'Dólares'), ('%', 'Porcentaje'), ('#', 'Número')], default='$', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-date'],
                'unique_together': {('user', 'metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RevenueTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('month_label', models.CharField(max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Mensual',
                'verbose_name_plural': 'Revenue Mensual',
                'ordering': ['month'],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
