# Generated by Django 6.0.3 on 2026-03-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('stripe', 'Stripe'), ('google_analytics', 'Google Analytics 4'), ('meta_ads', 'Meta Ads'), ('shopify', 'Shopify'), ('hubspot', 'HubSpot'), ('postgresql', 'PostgreSQL'), ('csv_upload', 'CSV Upload'), ('google_sheets', 'Google Sheets')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Error'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conector',
                'verbose_name_plural': 'Conectores',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'connector_type')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('failed', 'Fallido'), ('running', 'En progreso')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='connectors.dataconnector')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
